#!/bin/bash

#------------------#
# SLURM PARAMETERS #
#------------------#
ACCOUNT=""
PARTITION=""
QOS=""
TIME="05:00:00"
MEM="100G"
JOB_NAME="gnll"
MAIL=""
LOG_PATH=""
N_GPU="1"
SEED=100
MODEL_NAME="GNN4CD_model_GaussianNLL"
TARGET_TYPE="temperature"
LR_SCHEDULER="StepLR"

#------------------#
# WANDB PARAMETERS #
#------------------#

WANDB_PROJECT_NAME=""
WANDB_API_KEY=""
WANDB_USERNAME=""

#--------------------------------------------#
# PATHS (conda env, main, accelerate config) #
#--------------------------------------------#
SOURCE_PATH=""
ENV_PATH=""
MAIN_PATH=""
ACCELERATE_CONFIG_PATH=""

#-------------------------------#
# INPUT/OUTPUT FILES PARAMETERS #
#-------------------------------#
INPUT_PATH=""
OUTPUT_PATH=${LOG_PATH}
LOG_FILE="log.txt"
LOW_INPUT_FILE="low_input.npy"
OROG_FILE="orog.npy"
MASK_SEALAND_FILE="mask_sealand.npy"
COORDS_IJ_FILE="coords_ij.npy"
TARGET_FILE="target.npy"
METADATA_FILE="low_input_metadata.json"
GRAPH_FILE="low_high_graph.pkl"
DATASET_NAME="Dataset_Graph"
COLLATE_NAME="custom_collate_fn_graph"

#---------------------#
# TRAINING PARAMETERS #
#---------------------#
EPOCHS=150
BATCH_SIZE=64
LR_STEP_SIZE=25
LR=0.001
WEIGHT_DECAY=0.0

CTD_TRAINING=false
USE_ACCELERATE=true

#-----------------#
# LOSS PARAMETERS #
#-----------------#
LOSS_FN="GaussianNLLLoss"

#------------------#
# VALIDATION PLOTS #
#------------------#
MAKE_VAL_PLOTS=true
VAL_PLOT_FREQUENCY=1

#---------------------#
# TRAINING PARAMETERS #
#---------------------#
EPOCHS=150
BATCH_SIZE=64
LR_STEP_SIZE=25
LR=0.001
WEIGHT_DECAY=0.0

#----------------------------------------#
#             TRAINING PERIOD            #
#----------------------------------------#
TRAIN_YEAR_START=1961
TRAIN_MONTH_START=1
TRAIN_DAY_START=3
TRAIN_YEAR_END=1979
TRAIN_MONTH_END=12
TRAIN_DAY_END=29
VALIDATION_YEAR=1980

FIRST_YEAR=0
LAST_YEAR=0
N_VAL_YEARS=0

#-----------------#
# BOOLEAN OPTIONS #
#-----------------#
CTD_TRAINING=false
USE_ACCELERATE=true

#--------------do not change here below------------------

if [ ${USE_ACCELERATE} = true ] ; then
	USE_ACCELERATE="--use_accelerate"
else
	USE_ACCELERATE="--no-use_accelerate"
fi

if [ ${CTD_TRAINING} = true ] ; then
	CTD_TRAINING="--ctd_training"
else
	CTD_TRAINING="--no-ctd_training"
fi

if [ ${FINE_TUNING} = true ] ; then
	FINE_TUNING="--fine_tuning"
else
	FINE_TUNING="--no-fine_tuning"
fi

if [ ${MAKE_VAL_PLOTS} = true ] ; then
	MAKE_VAL_PLOTS="--make_val_plots"
else
	MAKE_VAL_PLOTS="--no-make_val_plots"
fi

