#!/bin/bash

#------------------#
# SLURM PARAMETERS #
#------------------#
TIME="04:20:00"
MEM="100G"
JOB_NAME="pr-NZ"
MAIL="sdigioia@ictp.it"

EXPERIMENT='ESD_pseudo_reality'
DOMAIN='NZ'
LOG_PATH="/leonardo_work/ICT26_ESP/sdigioia/CORDEX-ML/code_Vale/GNN4CD-CORDEXML/runs/${DOMAIN}_domain/${EXPERIMENT}/pr/mse_005qmse_005psd_land_coords_ij_new5/"
N_GPU="1"
SEED=100
MODEL_NAME="GNN4CD_model_mod1"
MODEL_TYPE="Rall"
TARGET_TYPE="precipitation"
LR_SCHEDULER="CosineAnnealingLR"
RUN_TYPE="CORDEXML_NZ"

#--------------------------------------------#
# PATHS (conda env, main, accelerate config) #
#--------------------------------------------#

ENV_PATH="/leonardo/pub/userexternal/sdigioia/sdigioia/env/RLenv" # conda env
SOURCE_PATH="/leonardo/home/userexternal/$USER/.bashrc"
ACCELERATE_CONFIG_PATH="/leonardo/home/userexternal/$USER/.cache/huggingface/accelerate/default_config_1.yaml"
MAIN_PATH="/leonardo_work/ICT26_ESP/sdigioia/CORDEX-ML/code_Vale/GNN4CD-CORDEXML"

#-------------------------------#
# INPUT/OUTPUT FILES PARAMETERS #
#-------------------------------#
INPUT_PATH="/leonardo_work/ICT26_ESP/sdigioia/CORDEX-ML/preprocessed/${DOMAIN}_domain/${EXPERIMENT}/pr/"
OUTPUT_PATH=${LOG_PATH}
LOG_FILE="log.txt"
LOW_INPUT_FILE="low_input.npy"
OROG_FILE="orog.npy"
MASK_SEALAND_FILE="mask_sealand.npy"
COORDS_IJ_FILE="coords_ij.npy"
TARGET_FILE="target.npy"
METADATA_FILE="low_input_metadata.json"
GRAPH_FILE="low_high_graph.pkl"
DATASET_NAME="Dataset_Graph"
COLLATE_NAME="custom_collate_fn_graph"

#---------------------#
# TRAINING PARAMETERS #
#---------------------#

EPOCHS=200
BATCH_SIZE=32
LR_STEP_SIZE=25
LR=0.0008
WEIGHT_DECAY=0.0
LOSS_FN="MSE_QMSE_PSD_Loss"
ALPHA=0.008
BETA=0.005

THRESHOLD=0.0
BINMIN=0.0
BINMAX=350
BINWIDTH=0.25
BINSCALE="log"

#WANDB_API_KEY="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"
WANDB_API_KEY="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"
WANDB_USERNAME="eirene1991"
WANDB_TEAM="climate-dl"
WANDB_PROJECT_NAME="CORDEX-ML"
#CHECKPOINT_CTD="/leonardo_work/ICT26_ESP/vblasone/test/HiResPrecipNet/runs/rounded/reg/reg_quantized_log05_alpha0025_nowd/checkpoint_19/"

#----------------------------------------#
#             TRAINING PERIOD            #
#----------------------------------------#
TRAIN_YEAR_START=1961
TRAIN_MONTH_START=1
TRAIN_DAY_START=3
TRAIN_YEAR_END=1979
TRAIN_MONTH_END=12
TRAIN_DAY_END=29
VALIDATION_YEAR=1980

FIRST_YEAR=0
LAST_YEAR=0
N_VAL_YEARS=0

#-----------------#
# BOOLEAN OPTIONS #
#-----------------#
CTD_TRAINING=false
FINE_TUNING=true
USE_ACCELERATE=true
MAKE_VAL_PLOTS=true


#--------------do not change here below------------------

if [ ${USE_ACCELERATE} = true ] ; then
	USE_ACCELERATE="--use_accelerate"
else
	USE_ACCELERATE="--no-use_accelerate"
fi

if [ ${CTD_TRAINING} = true ] ; then
	CTD_TRAINING="--ctd_training"
else
	CTD_TRAINING="--no-ctd_training"
fi

if [ ${FINE_TUNING} = true ] ; then
	FINE_TUNING="--fine_tuning"
else
	FINE_TUNING="--no-fine_tuning"
fi

if [ ${MAKE_VAL_PLOTS} = true ] ; then
	MAKE_VAL_PLOTS="--make_val_plots"
else
	MAKE_VAL_PLOTS="--no-make_val_plots"
fi

